/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import java.io.File;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import komunikacija.Komunikacija;
import model.Korisnik;
import model.ModelTabelePregledMojihPrijava;
import model.PrijavaVolontiranja;
import model.StatusPrijave;
import operacije.Operacije;
import transfer.KlijentskiZahtev;
import transfer.ServerskiOdgovor;

/**
 *
 * @author aleks
 */
public class PregledMojihPrijavaForma extends javax.swing.JFrame {
    
    List<PrijavaVolontiranja> lista;
    Korisnik ulogovaniKorisnik;

    /**
     * Creates new form Test
     */
    public PregledMojihPrijavaForma(List<PrijavaVolontiranja> lista, Korisnik ulogovaniKorisnik) {
        initComponents();
        setLocationRelativeTo(null);
        this.lista = lista;
        this.ulogovaniKorisnik = ulogovaniKorisnik;
        popuniTabelu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        btnNazad = new javax.swing.JButton();
        btnIzmeniPrijavu = new javax.swing.JButton();
        btnOtkaziPrijavu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pregled mojih prijava");
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\aleks\\OneDrive\\Dokumenti\\NetBeansProjects\\AO2026-Zajednicki\\src\\icon\\veciLogo.jpg")); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 112, 175));
        jLabel2.setText("PREGLED MOJIH PRIJAVA");

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabela);

        btnNazad.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnNazad.setForeground(new java.awt.Color(0, 112, 175));
        btnNazad.setText("Nazad");
        btnNazad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNazadActionPerformed(evt);
            }
        });

        btnIzmeniPrijavu.setBackground(new java.awt.Color(0, 112, 175));
        btnIzmeniPrijavu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnIzmeniPrijavu.setForeground(new java.awt.Color(255, 255, 255));
        btnIzmeniPrijavu.setText("Izmeni prijavu");
        btnIzmeniPrijavu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniPrijavuActionPerformed(evt);
            }
        });

        btnOtkaziPrijavu.setBackground(new java.awt.Color(0, 112, 175));
        btnOtkaziPrijavu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnOtkaziPrijavu.setForeground(new java.awt.Color(255, 255, 255));
        btnOtkaziPrijavu.setText("Otkazi prijavu");
        btnOtkaziPrijavu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOtkaziPrijavuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnNazad, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(btnIzmeniPrijavu, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnOtkaziPrijavu, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIzmeniPrijavu)
                    .addComponent(btnOtkaziPrijavu))
                .addGap(18, 18, 18)
                .addComponent(btnNazad)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(326, 326, 326))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNazadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNazadActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnNazadActionPerformed

    private void btnIzmeniPrijavuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniPrijavuActionPerformed
        // TODO add your handling code here:
        int row = tabela.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Greska! Morate selektovati prijavu koju zelite da izmenite!", "Greska", JOptionPane.ERROR_MESSAGE);
        } else {
            PrijavaVolontiranja p = lista.get(row);
            
            if (p.getStatusPrijave() != StatusPrijave.U_OBRADI) {
                JOptionPane.showMessageDialog(this, "Greska! Moguće je menjati samo prijave koje su maksimalno 24h do datuma smene!", "Greska", JOptionPane.ERROR_MESSAGE);
            }
            else {
                new IzmenaPrijaveZaVolontiranjeForma(p, lista, this).setVisible(true);
            }
        }
    }//GEN-LAST:event_btnIzmeniPrijavuActionPerformed

    private void btnOtkaziPrijavuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOtkaziPrijavuActionPerformed
        // TODO add your handling code here:
        int row = tabela.getSelectedRow();
        
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Greska! Morate selektovati prijavu koju zelite da otkazete!", "Greska", JOptionPane.ERROR_MESSAGE);
        } else {
            PrijavaVolontiranja p = lista.get(row);
            
            if (p.getStatusPrijave() != StatusPrijave.U_OBRADI) {
                JOptionPane.showMessageDialog(this, "Greska! Moguće je menjati samo prijave u obradi!", "Greska", JOptionPane.ERROR_MESSAGE);
            }
            else {
                
                int izbor = JOptionPane.showConfirmDialog(this, "Da li ste sigurni da želite da otkažete prijavu?", "Potvrda", JOptionPane.YES_NO_OPTION);
                
                if(izbor == JOptionPane.YES_OPTION) {
                    KlijentskiZahtev kz = new KlijentskiZahtev(Operacije.OTKAZ_PRIJAVE, p);
                    
                    Komunikacija.getInstance().posaljiZahtev(kz);
                    
                    ServerskiOdgovor so = Komunikacija.getInstance().primiOdgovor();
                    
                    if(so.getPoruka().toUpperCase().equals("USPESNO OBRISANA PRIJAVA")) {
                        obrisiFajlKlijenta(p);
                        
                        lista.remove(row);
                        popuniTabelu();
                        
                        JOptionPane.showMessageDialog(this, "Uspesno obrisana prijava!", "Obavestenje", JOptionPane.INFORMATION_MESSAGE);
                    }
                    else {
                        JOptionPane.showMessageDialog(this, "Greska! Greska pri brisanju prijave za volontiranj!", "Greska", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }
        }
    }//GEN-LAST:event_btnOtkaziPrijavuActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmeniPrijavu;
    private javax.swing.JButton btnNazad;
    private javax.swing.JButton btnOtkaziPrijavu;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables

    protected void popuniTabelu() {
        ModelTabelePregledMojihPrijava mtpmp = new ModelTabelePregledMojihPrijava(lista);
        tabela.setModel(mtpmp);
    }

    private void obrisiFajlKlijenta(PrijavaVolontiranja p) {
        String folder = "prijave_txt";

        String nazivFajla = "prijava_" + p.getIme().toLowerCase() + "_" + p.getPrezime().toLowerCase() + "_" + p.getDatumVolontiranja() + ".txt";

        File fajl = new File(folder, nazivFajla);
        if (fajl.exists()) {
            if (fajl.delete()) {
                System.out.println("Fajl uspešno obrisan: " + fajl.getName());
            } else {
                System.out.println("Greška pri brisanju fajla: " + fajl.getName());
            }
        } else {
            System.out.println("Fajl ne postoji: " + fajl.getName());
        }
    }

    public JTable getTabela() {
        return tabela;
    }

    public void setTabela(JTable tabela) {
        this.tabela = tabela;
    }

}
