/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import java.io.File;
import java.io.FileOutputStream;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.JOptionPane;
import komunikacija.Komunikacija;
import model.Korisnik;
import model.Pozicija;
import model.PrijavaVolontiranja;
import model.Smena;
import operacije.Operacije;
import transfer.KlijentskiZahtev;
import transfer.ServerskiOdgovor;

/**
 *
 * @author aleks
 */
public class PrijavaZaVolontiranjeForma extends javax.swing.JFrame {
    
    Korisnik ulogovaniKorisnik;

    /**
     * Creates new form Test
     */
    public PrijavaZaVolontiranjeForma(Korisnik ulogovaniKorisnik) {
        initComponents();
        setLocationRelativeTo(null);
        popuniComboBox();
        this.ulogovaniKorisnik = ulogovaniKorisnik;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnPosalji = new javax.swing.JButton();
        btnNazad = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtDatumVolontiranja = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cmbSmena = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        cmbPozicija = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Prijava za volontiranje");
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\aleks\\OneDrive\\Dokumenti\\NetBeansProjects\\AO2026-Zajednicki\\src\\icon\\veciLogo.jpg")); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnPosalji.setBackground(new java.awt.Color(0, 112, 175));
        btnPosalji.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnPosalji.setForeground(new java.awt.Color(255, 255, 255));
        btnPosalji.setText("Posalji");
        btnPosalji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPosaljiActionPerformed(evt);
            }
        });

        btnNazad.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnNazad.setForeground(new java.awt.Color(0, 112, 175));
        btnNazad.setText("Nazad");
        btnNazad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNazadActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 112, 175));
        jLabel2.setText("PRIJAVA ZA VOLONTIRANJE");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setText("Datum volontiranja:");

        txtDatumVolontiranja.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtDatumVolontiranja.setForeground(new java.awt.Color(102, 102, 102));
        txtDatumVolontiranja.setText("dd/mm/yyyy");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel4.setText("Smena:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel8.setText("Pozicija:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(17, 17, 17))
                    .addComponent(jLabel3)
                    .addComponent(txtDatumVolontiranja, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(cmbSmena, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btnPosalji, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnNazad, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(cmbPozicija, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(447, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDatumVolontiranja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbSmena, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbPozicija, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPosalji, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNazad, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPosaljiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPosaljiActionPerformed
        // TODO add your handling code here:
        try {
            PrijavaVolontiranja p = new PrijavaVolontiranja();
            p.setIme(ulogovaniKorisnik.getIme().trim());
            p.setPrezime(ulogovaniKorisnik.getPrezime().trim());
            p.setJmbg(ulogovaniKorisnik.getJmbg().trim());
            p.setEmail(ulogovaniKorisnik.getEmail().trim());

            LocalDate datumVolontiranja = LocalDate.parse(txtDatumVolontiranja.getText(), DateTimeFormatter.ofPattern("dd/MM/yyyy"));
            p.setDatumVolontiranja(datumVolontiranja);

            p.setSmena(Smena.valueOf(String.valueOf(cmbSmena.getSelectedItem())));
            p.setPozicija(Pozicija.valueOf(String.valueOf(cmbPozicija.getSelectedItem())));

            p.setDatumPrijave(LocalDate.now());

            KlijentskiZahtev kz = new KlijentskiZahtev(Operacije.PRIJAVA_ZA_VOLONTIRANJE, p);

            Komunikacija.getInstance().posaljiZahtev(kz);

            ServerskiOdgovor so = Komunikacija.getInstance().primiOdgovor();
            
            if (so.getPoruka().toUpperCase().equals("USPESNO STE SE PRIJAVILI")) {
                byte[] data = (byte[]) so.getOdgovor();

                String naziv = "prijava_" + ulogovaniKorisnik.getIme().toLowerCase() + "_" + ulogovaniKorisnik.getPrezime().toLowerCase() + "_" + p.getDatumVolontiranja() + ".txt";

                String folder = "prijave_txt";
                File dir = new File(folder);
                if (!dir.exists()) {
                    dir.mkdirs();
                }

                File klijentFajl = new File(dir, naziv);

                try ( FileOutputStream fos = new FileOutputStream(klijentFajl)) {
                    fos.write(data);
                } catch (Exception ex) {
                    ex.printStackTrace();
                    JOptionPane.showMessageDialog(this, "Neuspešno čuvanje fajla na klijentu!", "Greska", JOptionPane.ERROR_MESSAGE);
                    return;
                }

                JOptionPane.showMessageDialog(this, "Uspesno ste se prijavili za volontiranje na Asutralion Open-u 2026", "Obavestenje", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            }
            else {
                List<String> listaGresaka = (List<String>) so.getOdgovor();
                
                StringBuilder sb = new StringBuilder("Došlo je do sledećih gresaka:\n\n");
                
                for(String g: listaGresaka) {
                    sb.append("- ").append(g).append("\n");
                }
                
                JOptionPane.showMessageDialog(this, sb.toString(), "Greska", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Greska! Greska pri unosu!", "Greska", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnPosaljiActionPerformed

    private void btnNazadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNazadActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnNazadActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNazad;
    private javax.swing.JButton btnPosalji;
    private javax.swing.JComboBox<String> cmbPozicija;
    private javax.swing.JComboBox<String> cmbSmena;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtDatumVolontiranja;
    // End of variables declaration//GEN-END:variables

    private void popuniComboBox() {
        for(Smena smena : Smena.values()) {
            cmbSmena.addItem(String.valueOf(smena));
        }
        cmbSmena.setSelectedIndex(-1);
        
        for(Pozicija pozicija : Pozicija.values()) {
            cmbPozicija.addItem(String.valueOf(pozicija));
        }
        cmbPozicija.setSelectedIndex(-1);
    }
}
